def capitalize_family_genus(family_list):
    result = {}
    for item in family_list:
        parts = item.split('_')
        if len(parts) >= 2:
            family = parts[0]
            genus = parts[1]
            result[genus.capitalize()] = family.capitalize()
        else:
            print(f"Formato incorrecto en el elemento: {item}")
    return result

genus_family = [
    "thamnophilidae_euchrepomis", "thamnophilidae_cymbilaimus", "thamnophilidae_frederickena", "thamnophilidae_taraba", "thamnophilidae_sakesphorus",
    "thamnophilidae_thamnophilus", "thamnophilidae_megastictus", "thamnophilidae_neoctantes", "thamnophilidae_clytoctantes", "thamnophilidae_thamnistes", "thamnophilidae_dysithamnus",
    "thamnophilidae_thamnomanes", "thamnophilidae_xenornis", "thamnophilidae_isleria", "thamnophilidae_pygiptila", "thamnophilidae_epinecrophylla", "thamnophilidae_myrmotherula",
    "thamnophilidae_dichrozona", "thamnophilidae_herpsilochmus", "thamnophilidae_microrhopias", "thamnophilidae_formicivora", "thamnophilidae_drymophila", "thamnophilidae_hypocnemis",
    "thamnophilidae_cercomacroides", "thamnophilidae_cercomacra", "thamnophilidae_pyriglena", "thamnophilidae_myrmoborus", "thamnophilidae_hypocnemoides", "thamnophilidae_myrmochanes",
    "thamnophilidae_gymnocichla", "thamnophilidae_sclateria", "thamnophilidae_percnostola", "thamnophilidae_myrmelastes", "thamnophilidae_myrmeciza", "thamnophilidae_poliocrania",
    "thamnophilidae_sipia", "thamnophilidae_sciaphylax", "thamnophilidae_aprositornis", "thamnophilidae_myrmophylax", "thamnophilidae_ammonastes", "thamnophilidae_myrmornis",
    "thamnophilidae_pithys", "thamnophilidae_gymnopithys", "thamnophilidae_rhegmatorhina", "thamnophilidae_hylophylax",
    "thamnophilidae_willisornis", "thamnophilidae_phlegopsis", "thamnophilidae_phaenostictus", "thamnophilidae_oneillornis",
    "conopophagidae_conopophaga", "conopophagidae_pittasoma", "grallaridae_grallaria", "grallaridae_hylopezus", "grallaridae_myrmothera", "grallaridae_grallaricula",
    "rhinocryptidae_liosceles", "rhinocryptidae_acropternis", "rhinocryptidae_myornis", "rhinocryptidae_scytalopus"
    "formicariidae_formicarius", "formicariidae_chamaeze", "furnariidae_sclerurus", "furnariidae_certhiasomus", "furnariidae_sittasomus", "furnariidae_deconychura",
    "furnariidae_dendrocincla", "furnariidae_glyphorynchus", "icteridae_amblycercus", "icteridae_psarocolius", "icteridae_cacicus", "icteridae_amblycercus", "icteridae_icterus",
    "icteridae_dives", "icteridae_macroagelaius", "icteridae_gymnomystax", "icteridae_hypopyrrhus", "icteridae_lampropsar", "icteridae_chrysomus", "icteridae_molothrus",
    "icteridae_quiscalus", "icteridae_dolichonyx", "icteridae_sturnella", "icteridae_leistes",
    "furnariidae_nasica", "furnariidae_dendrexetastes", "furnariidae_dendrocolaptes", "furnariidae_hylexetastes", "furnariidae_xiphocolaptes",
    "furnariidae_xiphorhynchuss", "furnariidae_dendroplex", "furnariidae_campylorhamphus", "furnariidae_drymotoxeres", "furnariidae_lepidocolaptes",
    "furnariidae_xenops", "furnariidae_microxenops", "furnariidae_berlepschia", "furnariidae_pseudocolaptes", "furnariidae_premnornis", "furnariidae_furnarius",
    "furnariidae_lochmias", "furnariidae_cinclodes", "furnariidae_anabazenops", "furnariidae_philydor", "furnariidae_anabacerthia", "furnariidae_syndactyla",
    "furnariidae_ancistrops", "furnariidae_clibanornis", "furnariidae_thripadectes", "furnariidae_automolus", "furnariidae_premnoplex", "furnariidae_margarornis",
    "furnariidae_leptasthenura", "furnariidae_phacellodomus", "furnariidae_hellmayrea", "furnariidae_asthenes", "furnariidae_metopothrix", "furnariidae_xenerpestes",
    "furnariidae_siptornis", "furnariidae_thripophaga", "furnariidae_cranioleuca", "furnariidae_certhiaxis", "furnariidae_mazaria", "furnariidae_synallaxis",
    "furnariidae_dendroma", "sapayoidae_sapayoa", "tyrannidae_phyllomyias", "tyrannidae_myiopagis", "tyrannidae_tyrannulus", "tyrannidae_elaenia", "tyrannidae_ornithion", "tyrannidae_mecocerculus",
    "tyrannidae_camptostoma", "tyrannidae_anairetes", "tyrannidae_uromyas", "tyrannidae_serpophaga", "tyrannidae_phaeomyias", "tyrannidae_capsiempis", "tyrannidae_polystictus", "tyrannidae_pseudocolopteryx",
    "tyrannidae_pseudotriccus", "tyrannidae_corythopis", "tyrannidae_euscarthmus", "tyrannidae_stigmatura",
    "tyrannidae_zimmerius", "tyrannidae_phylloscartes", "tyrannidae_mionectes", "tyrannidae_leptopogon", "tyrannidae_sublegatus", "tyrannidae_inezia", "tyrannidae_myiotriccus",
    "tyrannidae_myiornis", "tyrannidae_oncostoma", "tyrannidae_lophotriccus", "tyrannidae_atalotriccus", "tyrannidae_hemitriccus", "tyrannidae_poecilotriccus",
    "tyrannidae_todirostrum", "tyrannidae_cnipodectes", "tyrannidae_rhynchocyclus", "tyrannidae_tolmomyias", "tyrannidae_platyrinchus", "tyrannidae_neopipo",
    "tyrannidae_myiophobus", "tyrannidae_pyrrhomyias", "tyrannidae_hirundinea", "tyrannidae_nephelomyias", "tyrannidae_lathrotriccus", "tyrannidae_aphanotriccus",
    "tyrannidae_cnemotriccus", "tyrannidae_empidonax", "tyrannidae_contopus", "tyrannidae_mitrephanes", "tyrannidae_sayornis", "tyrannidae_pyrocephalus", "tyrannidae_knipolegus",
    "tyrannidae_ochthornis", "tyrannidae_satrapa", "tyrannidae_muscisaxicola", "tyrannidae_agriornis", "tyrannidae_myiotheretes", "tyrannidae_cnemarchus", "tyrannidae_fluvicola",
    "tyrannidae_arundinicola", "tyrannidae_ochthoeca", "tyrannidae_colonia", "tyrannidae_legatus", "tyrannidae_muscigralla", "tyrannidae_machetornis", "tyrannidae_myiozetetes",
    "tyrannidae_phelpsia", "tyrannidae_pitangus", "tyrannidae_conopias", "tyrannidae_myiodynastes", "tyrannidae_megarynchus", "tyrannidae_tyrannopsis", "tyrannidae_empidonomus",
    "tyrannidae_tyrannus", "tyrannidae_rhytipterna", "tyrannidae_sirystes", "tyrannidae_myiarchus", "tyrannidae_ramphotrigon", "tyrannidae_attila", "tyrannidae_piprites",
    "tyrannidae_syrtidicola", "tyrannidae_pseudopipra", "cotingidae_pipreola", "cotingidae_ampelioides", "cotingidae_doliornis", "cotingidae_ampelion", "cotingidae_phoenicircus", "cotingidae_rupicola",
    "cotingidae_snowornis", "cotingidae_haematoderus", "cotingidae_querula", "cotingidae_pyroderus", "cotingidae_cephalopterus", "cotingidae_perissocephalus",
    "cotingidae_cotinga", "cotingidae_lipaugus", "cotingidae_porphyrolaema", "cotingidae_procnias", "cotingidae_xipholena", "cotingidae_carpodectes",
    "cotingidae_gymnoderus", "pipridae_tyranneutes", "pipridae_neopelma", "pipridae_chloropipo", "pipridae_chiroxiphia", "pipridae_masius", "pipridae_corapipo", "pipridae_xenopipo",
    "pipridae_cryptopipo", "pipridae_lepidothrix", "pipridae_heterocercus", "pipridae_manacus", "pipridae_pipra", "pipridae_machaeropterus", "pipridae_ceratopipra"
    "tityridae_tityra", "tityridae_schiffornis", "tityridae_laniocera", "tityridae_iodopleura", "tityridae_laniisoma", "tityridae_pachyramphus", "vireonidae_cyclarhis", "vireonidae_hylophilus",
    "vireonidae_vireolanius", "vireonidae_tunchiornis", "vireonidae_pachysylvia", "vireonidae_vireo", "corvidae_cyanolyca", "corvidae_cyanocorax", "alaudidae_eremophila",
    "hirundinidae_pygochelidon", "hirundinidae_alopochelidon", "hirundinidae_orochelidon", "hirundinidae_atticora", "hirundinidae_stelgidopteryx",
    "hirundinidae_progne", "hirundinidae_tachycineta", "hirundinidae_riparia", "hirundinidae_hirundo", "hirundinidae_petrochelidon", "troglodytidae_microcerculus", "troglodytidae_odontorchilus",
    "troglodytidae_troglodytes", "troglodytidae_cistothorus", "troglodytidae_campylorhynchus", "passerellidae_passerculus", "passerellidae_ammodramus", "passerellidae_chlorospingus",
    "passerellidae_atlapetes", "passerellidae_oreothraupis", "passerellidae_arremon", "passerellidae_zonotrichia", "passerellidae_spizella", "passerellidae_arremonops",
    "troglodytidae_pheugopedius", "troglodytidae_thryophilus", "troglodytidae_cantorchilus", "troglodytidae_cinnycerthia", "troglodytidae_henicorhina",
    "troglodytidae_cyphorhinus", "polioptilidae_microbates", "polioptilidae_ramphocaenus", "polioptilidae_polioptila", "donacobiidae_donacobius", "cinclidae_cinclus", "bombycillidae_bombycilla",
    "turdidae_myadestes", "turdidae_catharus", "turdidae_hylocichla", "turdidae_cichlopsis", "turdidae_entomodestes", "mimidae_dumetella", "mimidae_mimus", "motacillidae_anthus",
    "thraupidae_nemosia", "thraupidae_sericossypha", "thraupidae_parkerthraustes", "thraupidae_catamblyrhynchus", "thraupidae_chlorophanes", "thraupidae_iridophanes",
    "thraupidae_chrysothlypis", "thraupidae_heterospingus", "thraupidae_hemithraupis", "thraupidae_conirostrum", "thraupidae_sicalis", "thraupidae_catamenia",
    "thraupidae_geospizopsis", "thraupidae_volatinia", "thraupidae_diglossa", "thraupidae_conothraupis", "thraupidae_creurgops", "thraupidae_tachyphonus",
    "thraupidae_eucometis", "thraupidae_ramphocelus", "thraupidae_lanio", "thraupidae_cyanerpes", "thraupidae_tersina", "thraupidae_dacnis", "thraupidae_coryphospingus",
    "thraupidae_rhodospingus", "thraupidae_sporophila", "thraupidae_saltator", "thraupidae_emberizoides", "thraupidae_pseudospingus", "thraupidae_cnemoscopus",
    "thraupidae_kleinothraupis", "thraupidae_sphenopsis", "thraupidae_thlypopsis", "thraupidae_urothraupis", "thraupidae_coereba", "thraupidae_tiaris", "thraupidae_chlorochrysa",
    "thraupidae_paroaria", "thraupidae_schistochlamys", "thraupidae_cissopis", "thraupidae_calochaetes", "thraupidae_iridosornis", "thraupidae_pipraeidea", "thraupidae_dubusia",
    "thraupidae_anisognathus", "thraupidae_buthraupis", "thraupidae_cnemathraupis", "thraupidae_bangsia", "thraupidae_chlorornis", "thraupidae_tangara", "thraupidae_thraupis",
    "thraupidae_ixothraupis", "thraupidae_haplospiza", "thraupidae_melanospiza", "thraupidae_asemospiza", "pipridae_tyranneutes", "pipridae_neopelma", "pipridae_chloropipo",
    "pipridae_chiroxiphia", "pipridae_masius", "pipridae_corapipo", "pipridae_xenopipo", "pipridae_cryptopipo", "pipridae_lepidothrix", "pipridae_heterocercus", "pipridae_manacus",
    "pipridae_pipra", "pipridae_machaeropterus", "pipridae_ceratopipra", "formicariidae_formicarius", "formicariidae_chamaeza", "fringillidae_spinus", "fringillidae_euphonia",
    "fringillidae_chlorophonia", "fringillidae_spinus", "fringillidae_euphonia", "fringillidae_chlorophonia", "mitrospingidae_lamprospiza", "estrildidae_lonchura",
    "thraupidae_loriotus", "thraupidae_sporathraupis", "thraupidae_tephrophilus", "thraupidae_chalcothraupis", "thraupidae_stilpnia", "furnariidae_xiphorhynchus",
    "melanopareiidae_melanopareia", "onychorhynchidae_onychorhynchus", "onychorhynchidae_terenotriccus", "onychorhynchidae_myiobius", "passeridae_passer", "ploceidae_ploceus",
    "rhodinocichlidae_rosea", "rhinocryptidae_scytalopus", "rhodinocichlidae_rhodinocichla", "tityridae_tityra", "tyrannidae_uromyias", "rhamphastidae_aulacorhynchus",
    "rhamphastidae_ramphastos", "rhamphastidae_selenidera", "rhamphastidae_pteroglossus", "rhamphastidae_andigena", "capitonidae_capito", "capitonidae_eubucco", "picidae_picumnus",
    "picidae_melanerpes", "picidae_piculus", "picidae_celeus", "picidae_campephilus", "falconidae_micrastur", "falconidae_herpetotheres", "falconidae_ibycter", "falconidae_daptrius",
    "falconidae_caracara", "falconidae_milvago", "falconidae_falco", "psittacidae_touit", "psittacidae_bolborhynchus", "psittacidae_brotogeris", "psittacidae_forpus",
    "psittacidae_pionus", "psittacidae_ara"
]

suborder = {
    'Philepittidae': 'tiranni',
    'Eurylaimidae': 'tiranni',
    'Calyptomenidae': 'tiranni',
    'Sapayoidae': 'tiranni',
    'Pittidae': 'tiranni',
    'Pipridae': 'tiranni',
    'Cotingidae': 'tiranni',
    'Tityridae': 'tiranni',
    'Tyrannidae': 'tiranni',
    'Melanopareiidae': 'tiranni',
    'Conopophagidae': 'tiranni',
    'Thamnophilidae': 'tiranni',
    'Grallaridae': 'tiranni',
    'Rhinocryptidae': 'tiranni',
    'Formicariidae': 'tiranni',
    'Furnariidae': 'tiranni',
    'Onychorhynchidae': 'tiranni',
    'Donacobiidae': 'tiranni',
    'Menuridae': 'passeri',
    'Mitrospingidae': 'passeri',
    'Atrichornithidae': 'passeri',
    'Climacteridae': 'passeri',
    'Maluridae': 'passeri',
    'Passerellidae': 'passeri',
    'Meliphagidae': 'passeri',
    'Pardalotidae': 'passeri',
    'Petroicidae': 'passeri',
    'Orthonychidae': 'passeri',
    'Pomatostomidae': 'passeri',
    'Cinclosomatidae': 'passeri',
    'Neosittidae': 'passeri',
    'Pachycephalidae': 'passeri',
    'Dicruridae': 'passeri',
    'Oriolidae': 'passeri',
    'Artamidae': 'passeri',
    'Paradisaeidae': 'passeri',
    'Corvidae': 'passeri',
    'Cyanocorax': 'passeri',
    'Corcoracidae': 'passeri',
    'Irenidae': 'passeri',
    'Laniidae': 'passeri',
    'Vireonidae': 'passeri',
    'Ptilonorhynchidae': 'passeri',
    'Turnagridae': 'passeri',
    'Callaeidae': 'passeri',
    'Alaudidae': 'passeri',
    'Chloropseidae': 'passeri',
    'Aegithinidae': 'passeri',
    'Picathartidae': 'passeri',
    'Bombycillidae': 'passeri',
    'Ptilogonatidae': 'passeri',
    'Cinclidae': 'passeri',
    'Motacillidae': 'passeri',
    'Prunellidae': 'passeri',
    'Melanocharitidae': 'passeri',
    'Paramythiidae': 'passeri',
    'Passeridae': 'passeri',
    'Estrildidae': 'passeri',
    'Ploceidae': 'passeri',
    'Parulidae': 'passeri',
    'Thraupidae': 'passeri',
    'Peucedramidae': 'passeri',
    'Fringillidae': 'passeri',
    'Cardinalidae': 'passeri',
    'Drepanididae': 'passeri',
    'Emberizidae': 'passeri',
    'Nectariniidae': 'passeri',
    'Dicaeidae': 'passeri',
    'Mimidae': 'passeri',
    'Sittidae': 'passeri',
    'Certhiidae': 'passeri',
    'Troglodytidae': 'passeri',
    'Polioptilidae': 'passeri',
    'Paridae': 'passeri',
    'Aegithalidae': 'passeri',
    'Hirundinidae': 'passeri',
    'Regulidae': 'passeri',
    'Pycnonotidae': 'passeri',
    'Sylviidae': 'passeri',
    'Acrocephalidae': 'passeri',
    'Locustellidae': 'passeri',
    'Cettiidae': 'passeri',
    "Rhodinocichlidae": "passeri",
    'Phylloscopidae': 'passeri',
    'Cisticolidae': 'passeri',
    'Hypocoliidae': 'passeri',
    'Zosteropidae': 'passeri',
    'Paradoxornithidae': 'passeri',
    'Timaliidae': 'passeri',
    'Leiothrichidae': 'passeri',
    'Muscicapidae': 'passeri',
    'Turdidae': 'passeri',
    'Sturnidae': 'passeri',
    'Icteridae': 'passeri',
    'Capitonidae': 'Piciformes',
    'Rhamphastidae': 'Piciformes',
    'Psittacidae': 'Psittaciformes',
    'Falconidae': 'Falconiformes',
    'Picidae': 'Piciformes'
}
